window.weddingConfig={
  couple:{groom:'Jithin',bride:'Lydia'},
  wedding:{date:'2026-11-07',time:'15:30'},
  verse:{text:'He has made everything beautiful in its time.',reference:'Ecclesiastes 3:11'},
  ceremony:{
    mapsUrl:'https://www.google.com/maps/search/?api=1&query=St+Thomas+Jacobite+Syrian+Church+North+Paravur'
  },
  reception:{
    mapsUrl:'https://www.google.com/maps/search/?api=1&query=Sunny+Convention+Centre+North+Paravur'
  },
  music:{enabled:true,source:'assets/music/wedding.mp3',volume:.22},
  interaction:{resumeAfterInactivity:2000},
  animation:{speed:1,scenes:{
    opening:6200,scripture:6000,hero:9800,ceremony:7600,
    reception:7600,countdown:7000,closing:10500
  }},
  images:{
    opening:'assets/images/opening.png',
    scripture:'assets/images/scripture.png',
    hero:'assets/images/hero.png',
    ceremony:'assets/images/church.png',
    reception:'assets/images/reception.png',
    closing:'assets/images/hero.png',
    og:'assets/images/og-image.png'
  },
  theme:{background:'#0c0907',gold:'#b59661'}
};
