(() => {
'use strict';
const cfg=window.weddingConfig||{};const body=document.body;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const scenes=[...document.querySelectorAll('.scene')];
const labels={opening:'OPENING',scripture:'SCRIPTURE',hero:'JITHIN & LYDIA',ceremony:'HOLY MATRIMONY',reception:'CELEBRATION',countdown:'COUNTDOWN',closing:'FOREVER'};
const settings=cfg.sceneSettings||{};let current=0,started=false,timer=null,transitionTimer=null,countTimer=null,touchY=0;
function addUI(){const loader=document.createElement('div');loader.className='site-loader';loader.innerHTML='<div class="loader-mark">J &amp; L</div><div class="loader-date">07 · 11 · 2026</div><div class="loader-line"><span></span></div><div class="loader-label">THE STORY BEGINS</div>';document.body.prepend(loader);setTimeout(()=>loader.classList.add('is-hidden'),reduced?300:1500);
const tr=document.createElement('div');tr.className='scene-transition';tr.innerHTML='<div class="transition-label"><span id="transitionFrom"></span><i></i><span id="transitionTo"></span></div>';document.body.appendChild(tr);
const sound=document.createElement('button');sound.id='cinematicSound';sound.className='cinematic-sound';sound.type='button';sound.setAttribute('aria-label','Turn sound on');sound.innerHTML='♪ <span>OFF</span>';sound.addEventListener('click',toggleSound);document.body.appendChild(sound);}
function ui(){return{loader:document.querySelector('.site-loader'),tr:document.querySelector('.scene-transition'),sound:document.getElementById('cinematicSound'),from:document.getElementById('transitionFrom'),to:document.getElementById('transitionTo')}}
function clearTimer(){if(timer){clearTimeout(timer);timer=null}}function setSound(on){const b=ui().sound;if(b){b.innerHTML=`♪ <span>${on?'ON':'OFF'}</span>`;b.setAttribute('aria-label',on?'Turn sound off':'Turn sound on')}}
function playMusic(){const m=document.getElementById('music');if(!m||cfg.music?.enabled===false)return;m.volume=Number(cfg.music?.volume??.22);m.play().then(()=>setSound(true)).catch(()=>setSound(false))}
function toggleSound(){const m=document.getElementById('music');if(!m)return;if(m.paused)playMusic();else{m.pause();setSound(false)}}
function chrome(){const key=scenes[current]?.dataset.scene||'opening';const name=document.getElementById('sceneName');const bar=document.querySelector('.progress span');if(name)name.textContent=labels[key];if(bar)bar.style.width=`${current/(scenes.length-1)*100}%`;body.dataset.scene=key}
function schedule(){clearTimer();if(!started||reduced)return;const key=scenes[current]?.dataset.scene,s=settings[key]||{};if(s.auto===false||!s.duration||current>=scenes.length-1)return;timer=setTimeout(()=>go(current+1),Number(s.duration))}
function apply(i){current=Math.max(0,Math.min(i,scenes.length-1));scenes.forEach((s,n)=>{const active=n===current;s.classList.toggle('is-active',active);s.setAttribute('aria-hidden',active?'false':'true')});chrome();schedule()}
function go(i){if(!started)return;const target=Math.max(0,Math.min(i,scenes.length-1));if(target===current)return;clearTimer();const from=scenes[current]?.dataset.scene||'opening',to=scenes[target]?.dataset.scene||'opening';if(reduced){apply(target);return}const q=ui();q.from.textContent=labels[from];q.to.textContent=labels[to];q.tr.classList.remove('is-running');void q.tr.offsetWidth;q.tr.classList.add('is-running');clearTimeout(transitionTimer);transitionTimer=setTimeout(()=>apply(target),470)}
function enter(e){e?.preventDefault();if(started)return;started=true;body.classList.add('started','invitation-entered');playMusic();go(1)}
const enterBtn=document.getElementById('enter');if(enterBtn){enterBtn.onclick=null;enterBtn.addEventListener('click',enter)}
function next(){if(!started){enter();return}go(current+1)}function prev(){if(started)go(current-1)}
document.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>18)(e.deltaY>0?next:prev)()},{passive:true});document.addEventListener('keydown',e=>{if(e.target.closest('a,button'))return;if(['ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();next()}else if(['ArrowUp','PageUp'].includes(e.key)){e.preventDefault();prev()}else if(e.key.toLowerCase()==='m')toggleSound()});document.addEventListener('touchstart',e=>{touchY=e.changedTouches[0].clientY},{passive:true});document.addEventListener('touchend',e=>{const dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dy)>48)(dy<0?next:prev)()},{passive:true});
function countdown(){const target=Date.parse(`${cfg.wedding?.date||'2026-11-07'}T${cfg.wedding?.time||'15:30'}:00`);let t=Math.max(0,Math.floor((target-Date.now())/1000));const v=[Math.floor(t/86400),Math.floor(t%86400/3600),Math.floor(t%3600/60),t%60];['d','h','m','s'].forEach((id,i)=>{const n=document.getElementById(id);if(n)n.textContent=String(v[i]).padStart(2,'0')})}
addUI();apply(0);countdown();countTimer=setInterval(countdown,1000);setSound(false);addEventListener('pagehide',()=>{clearTimer();clearInterval(countTimer);clearTimeout(transitionTimer)},{once:true});
})();
